=== PauSolerValades/SAR/practicageneral3/xml/lista_pisos.dtd
<!ELEMENT pisos (piso)*>
<!ATTLIST pisos ult_id IDREF #REQUIRED>
<!ELEMENT piso (direccion, precio, habitaciones, banos, fianza, descripcion,fechaIn,fechaFin, tel, mail, nombre, fotos?, caracteristicas)>
<!ATTLIST piso id ID #REQUIRED>
<!ELEMENT direccion (#PCDATA)>
<!ATTLIST direccion prov (A|B|C) #REQUIRED>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT habitaciones (#PCDATA)>
<!ELEMENT banos (#PCDATA)>
<!ELEMENT fianza (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT fechaIn (#PCDATA)>
<!ELEMENT fechaFin (#PCDATA)>
<!ELEMENT tel (#PCDATA)>
<!ELEMENT mail (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>

<!ELEMENT fotos (foto)*>
<!ATTLIST fotos ult_id IDREF #REQUIRED>
<!ATTLIST fotos tiene (si|no) "no">
<!ELEMENT foto (#PCDATA)>
<!ATTLIST foto id ID #REQUIRED>

<!ELEMENT caracteristicas (caracteristica)*>
<!ATTLIST caracteristicas lavavajillas (1|0) "1">
<!ATTLIST caracteristicas wifi (1|0) "1">
<!ATTLIST caracteristicas terraza (1|0) "1">
<!ATTLIST caracteristicas la (1|0) "1">

=== PauSolerValades/SAR/practicageneral3/xml/lista_pisos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE visitas SYSTEM "lista_pisos.dtd">

<pisos ult_id="9">
    <piso id = "1">
        <direccion>noseque kalea</direccion>
        <precio>300</precio>
        <habitaciones> 2 </habitaciones>
        <fianza> 600 </fianza>
        <descripcion> este piso claramente no existse, quiero decir, tu has visto el precio? </descripcion>
        <tel>6666666</tel>
        <nombre>Aitor tilla</nombre>
        <mail>satan@atana.xsa</mail>
        <fotos ult_id = "0" tiene = "si">
            <foto id = "0">url1</foto>
        </fotos>
        <caracteristicas 
            lavavajillas="0"
            wifi = "1"
            terraza = "1"
            lavadora = "1"        
            >
        </caracteristicas>
    </piso>
</pisos>
